// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: proto/greet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting to the provided name.
	Simple(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	SimpleToStream(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SimpleToStreamClient, error)
	StreamToSimple(ctx context.Context, opts ...grpc.CallOption) (Greeter_StreamToSimpleClient, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) Simple(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/mygrpc.Greeter/Simple", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SimpleToStream(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SimpleToStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[0], "/mygrpc.Greeter/SimpleToStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSimpleToStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_SimpleToStreamClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSimpleToStreamClient struct {
	grpc.ClientStream
}

func (x *greeterSimpleToStreamClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) StreamToSimple(ctx context.Context, opts ...grpc.CallOption) (Greeter_StreamToSimpleClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[1], "/mygrpc.Greeter/StreamToSimple", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterStreamToSimpleClient{stream}
	return x, nil
}

type Greeter_StreamToSimpleClient interface {
	Send(*HelloRequest) error
	CloseAndRecv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterStreamToSimpleClient struct {
	grpc.ClientStream
}

func (x *greeterStreamToSimpleClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterStreamToSimpleClient) CloseAndRecv() (*HelloReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	// Sends a greeting to the provided name.
	Simple(context.Context, *HelloRequest) (*HelloReply, error)
	SimpleToStream(*HelloRequest, Greeter_SimpleToStreamServer) error
	StreamToSimple(Greeter_StreamToSimpleServer) error
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) Simple(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Simple not implemented")
}
func (UnimplementedGreeterServer) SimpleToStream(*HelloRequest, Greeter_SimpleToStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SimpleToStream not implemented")
}
func (UnimplementedGreeterServer) StreamToSimple(Greeter_StreamToSimpleServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamToSimple not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_Simple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Simple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mygrpc.Greeter/Simple",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Simple(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SimpleToStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).SimpleToStream(m, &greeterSimpleToStreamServer{stream})
}

type Greeter_SimpleToStreamServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterSimpleToStreamServer struct {
	grpc.ServerStream
}

func (x *greeterSimpleToStreamServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_StreamToSimple_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).StreamToSimple(&greeterStreamToSimpleServer{stream})
}

type Greeter_StreamToSimpleServer interface {
	SendAndClose(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterStreamToSimpleServer struct {
	grpc.ServerStream
}

func (x *greeterStreamToSimpleServer) SendAndClose(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterStreamToSimpleServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mygrpc.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Simple",
			Handler:    _Greeter_Simple_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SimpleToStream",
			Handler:       _Greeter_SimpleToStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamToSimple",
			Handler:       _Greeter_StreamToSimple_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/greet.proto",
}
